require("myconfig.plugin_config.treesitter_config")
require("myconfig.plugin_config.lsp")
require('myconfig.plugin_config.gitblame')
require('myconfig.plugin_config.prettier_config')
require("myconfig.plugin_config.ruby_config")
require("myconfig.plugin_config.dap_config")
-- require('myconfig.plugin_config.rust_config')
require('myconfig.plugin_config.gitblame')
require('myconfig.plugin_config.tagbar')
